# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [16]:
import numpy as np
ar1 = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
line = ar1[:5,:]
print(line)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [17]:
ar2 = ar1[:,1:]
means = np.mean(ar2, axis=0)
mins = np.min(ar2, axis=0)
maxs = np.max(ar2, axis=0)
medians = np.median(ar2, axis=0)
print('Среднее значение', means,'минимум:', mins, 'максимум:', maxs, 'медиана:', medians )

Среднее значение [2.16010017e+04 9.05528000e+00] минимум: [0 1] максимум: [2147483647         39] медиана: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [18]:
qv = np.quantile(ar1[:,1], q=0.75, axis=0)
print(ar1[ar1[:, 1] <= qv])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [370915      5      4]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [19]:
print(len(ar1[ar1[:, 1] == 0]))
ar1[ar1[:, 1] == 0] = 1

479


In [20]:
print(len(ar1[ar1[:, 1] == 0]))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [21]:
print(len(np.unique(ar1[:, 0])))

99522


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [22]:
print(len(np.unique(ar1[:, 2])))
print(*np.unique(ar1[:, 2]))

37
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 37 39


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [24]:
ar3 = ar1[ar1[:, 2] <= 5]
ar3

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [30]:
ar_s = ar1[ar1[:, 1].argsort()]
ar_s = ar_s[-100:]
np.mean(ar_s[:, 2])

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [31]:
quantity = 10 
index = np.random.choice(ar1.shape[0], quantity, replace=False)
ar1[index]

array([[316405,     45,      4],
       [275911,      3,      2],
       [260531,     15,      6],
       [ 67257,     50,     10],
       [490269,     10,      4],
       [149465,     40,      7],
       [ 33311,      5,      7],
       [105237,     20,     11],
       [ 12984,     15,      6],
       [176534,     30,      6]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [32]:
ar1 = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
mn = np.mean(ar1[:, 2])
ls = len(ar1[ar1[:, 2] < mn])
per = 100 * ls / len(ar1)
per

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [33]:
ar2 = ar1.copy()
simple_recipe = [1 if (row[1] <= 20) & (row[2] <= 5) else 0 for row in ar2]
new_ar = np.insert(ar2, 3, simple_recipe, axis=1)
print(new_ar)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [370915      5      4      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [34]:
cnt = (new_ar[:,3] == 1)
len(ar1[cnt, :])/ len(new_ar) * 100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.